# Generated by Django 3.1.6 on 2021-02-17 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NHLTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(choices=[('Anaheim Ducks', 'Anaheim Ducks'), ('Arizona Coyotes', 'Arizona Coyotes'), ('Boston Bruins', 'Boston Bruins'), ('Buffalo Sabres', 'Buffalo Sabres'), ('Calgary Flames', 'Calgary Flames'), ('Carolina Hurricanes', 'Carolina Hurricanes'), ('Chicago Blackhawks', 'Chicago Blackhawks'), ('Colorado Avalanche', 'Colorado Avalanche'), ('Columbus Blue Jackets', 'Columbus Blue Jackets'), ('Dallas Stars', 'Dallas Stars'), ('Detroit Red Wings', 'Detroit Red Wings'), ('Edmonton Oilers', 'Edmonton Oilers'), ('Florida Panthers', 'Florida Panthers'), ('Los Angeles Kings', 'Los Angeles Kings'), ('Minnesota Wild', 'Minnesota Wild'), ('Montréal Canadiens', 'Montréal Canadiens'), ('Nashville Predators', 'Nashville Predators'), ('New Jersey Devils', 'New Jersey Devils'), ('New York Islanders', 'New York Islanders'), ('New York Rangers', 'New York Rangers'), ('Ottawa Senators', 'Ottawa Senators'), ('Philadelphia Flyers', 'Philadelphia Flyers'), ('Pittsburgh Penguins', 'Pittsburgh Penguins'), ('San Jose Sharks', 'San Jose Sharks'), ('St. Louis Blues', 'St. Louis Blues'), ('Tampa Bay Lightning', 'Tampa Bay Lightning'), ('Toronto Maple Leafs', 'Toronto Maple Leafs'), ('Vancouver Canucks', 'Vancouver Canucks'), ('Vegas Golden Knights', 'Vegas Golden Knights'), ('Washington Capitals', 'Washington Capitals'), ('Winnipeg Jets', 'Winnipeg Jets')], max_length=21)),
                ('team_id', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NHLGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='tripplanner.nhlteam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='tripplanner.nhlteam')),
            ],
        ),
    ]
