# Generated by Django 3.1.6 on 2021-02-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFLTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('section', models.CharField(max_length=5)),
                ('seat', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='NHLGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_name', models.CharField(max_length=50)),
                ('home_team_id', models.IntegerField()),
                ('away_team_name', models.CharField(max_length=50)),
                ('away_team_id', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
