# Generated by Django 3.1.6 on 2021-02-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripplanner', '0002_auto_20210225_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='distance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
