# Generated by Django 3.1.6 on 2021-03-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripplanner', '0003_distance_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='distance',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
